image: gitpod/workspace-dotnet

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Run
    command: dotnet run

vscode:
  extensions:
    - muhammad-sammy.csharp
